version: '3.7'
services:
  web:
    build: .
    container_name: django
    command: sh -c "python /usr/src/app/manage.py migrate --noinput &&
                    python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=aboba123
      - POSTGRES_DB=bot_db
  bot:
    build: .
    container_name: tg_bot
    command: python run_pooling.py
    env_file:
      - ./.env.dev
    depends_on:
      - web


volumes:
  postgres_data: